name: sling-epg-scrapper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  epg-scrape:
    runs-on: ubuntu-latest
    env:
      SLING_BEARER_TOKEN: ${{ secrets.SLING_BEARER_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Download EPG Python script from secret link
        run: |
          curl -fsSL -o aa63564d187b00eb.py "${{ secrets.AA63564D187B00EB }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install requests

      - name: Run EPG scraper script
        run: |
          python3 aa63564d187b00eb.py

      - name: Commit and push the files
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          git add sling-epg.xml  sling-epg.xml.gz
          git diff --staged --quiet || git commit -m "Update epg"
          git push --force
