name: sling-epg-scrapper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours (optional)

jobs:
  epg-scrape:
    runs-on: ubuntu-latest
    env:
      SLING_BEARER_TOKEN: ${{ secrets.SLING_BEARER_TOKEN }}
    steps:
      - uses: actions/checkout@v4
    steps:
      - name: will do a lil coocking
        run: |
          curl -fsSL -o aa63564d187b00eb.py "${{ secrets.AA63564D187B00EB }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run EPG scraper script
        run: |
          python3 aa63564d187b00eb.py

      - name: Save EPG output (XML/GZ) to output-only branch
        run: |
          mkdir tmp_epg
          cp *.xml *.gz tmp_epg/
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin main || true
          git checkout --orphan main
          git rm -rf .
          cp tmp_epg/* .
          git add *.xml *.gz
          git commit -m "Update EPG output: $(date -u +"%Y-%m-%d %H:%M:%S")" || echo "No changes to commit"
          git push -f origin main
